#!/usr/bin/env sh
set -eu

python3 -m pip install -r lib/requirements.txt

if [ -f bin/tectonic ]; then
  exit 0
fi

mkdir -p bin
tmp="$(mktemp -d)"
cd "$tmp"
curl -fsSL https://drop-sh.fullyjustified.net | sh
mv tectonic "$OLDPWD/bin/tectonic"
chmod +x "$OLDPWD/bin/tectonic"
